version: "3.7"

services:
  restapi-torips-db:
    container_name: restapi-torips-db
    image: postgres:15-alpine
    env_file:
      - ./db.env

  restapi-torips-api:
    container_name: restapi-torips-api
    build: ./api
    env_file:
      - ./api.env
      - ./db.env
    ports:
      - 3000:3000
    links:
      - restapi-torips-db
    depends_on:
      - restapi-torips-db

  restapi-torips-web:
    image: python3.10-alpine
    container_name: restapi-torips-web
    working_dir: /app
    ports:
      - 3000:80
    links:
      - restapi-torips-api
