name: "Security issues"

on:
  pull_request:
    branches: [ master, develop ]
jobs:
  Node-Security-Issues:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        version: [19]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Check dependencies
        run: cd api; yarn audit


  Python-Security-Issues:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Check packages
        uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          inputs: web-server/requirements.txt